#!/usr/bin/env python3
"""Generate a SYNTHETIC OSHA ITA 300A fixture.

THIS SCRIPT PRODUCES FAKE DATA. Nothing it writes is an observation of anything.
It exists so the pipeline and the tests can run without a network connection and
so the estimators can be checked against known ground truth. No number produced
from this fixture may be reported as a finding, and the pipeline stamps any run
against it as synthetic.

Every generated file carries a header comment line declaring it synthetic. The
loader tolerates that line because it begins with ``#``... which the CSV reader
does not, so the header is instead written to a sibling ``.HEADER.txt`` file and
duplicated into ``README.md``, keeping the CSV itself schema-valid.

What is simulated, and why
--------------------------
The generator reproduces four structural features of the real data so the code
paths that matter are exercised:

1. A realistic-ish log-normal spread of establishment size.
2. Recordable counts from a zero-inflated negative binomial with known
   ``mu``, ``alpha`` and ``pi``, so :mod:`ehs_osha.countmodels` can be checked
   for recovery of parameters it was not told.
3. A small fraction of filings with hours values inflated by a power of ten,
   mimicking the data-entry failure mode the plausibility screen targets.
4. Two schema eras (pre-2023 and 2023+) with different column order, so the
   harmonisation code is genuinely tested.

Usage:
    python synthetic/generate_fixture.py
    python synthetic/generate_fixture.py --out synthetic/fixture --n 4000
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence

import numpy as np

SYNTHETIC_HEADER = (
    "SYNTHETIC DATA -- NOT REAL OSHA FILINGS. Generated by "
    "synthetic/generate_fixture.py for testing only. Any statistic computed "
    "from this file is a property of the generator, not of any workplace, "
    "establishment, industry or regulator. Do not cite."
)

PRE2023_COLUMNS: Sequence[str] = (
    "id", "company_name", "establishment_name", "ein", "street_address", "city",
    "state", "zip_code", "naics_code", "industry_description",
    "annual_average_employees", "total_hours_worked", "no_injuries_illnesses",
    "total_deaths", "total_dafw_cases", "total_djtr_cases", "total_other_cases",
    "total_dafw_days", "total_djtr_days", "total_injuries", "total_poisonings",
    "total_respiratory_conditions", "total_skin_disorders", "total_hearing_loss",
    "total_other_illnesses", "establishment_id", "establishment_type", "size",
    "year_filing_for", "created_timestamp", "change_reason",
)

POST2023_COLUMNS: Sequence[str] = (
    "id", "establishment_name", "establishment_id", "ein", "company_name",
    "street_address", "city", "state", "zip_code", "naics_code", "naics_year",
    "industry_description", "establishment_type", "size",
    "annual_average_employees", "total_hours_worked", "no_injuries_illnesses",
    "total_deaths", "total_dafw_cases", "total_djtr_cases", "total_other_cases",
    "total_dafw_days", "total_djtr_days", "total_injuries",
    "total_skin_disorders", "total_respiratory_conditions", "total_poisonings",
    "total_hearing_loss", "total_other_illnesses", "change_reason",
    "created_timestamp", "year_filing_for",
)


@dataclass(frozen=True)
class GeneratorParams:
    """Ground-truth parameters the fixture is generated from.

    Attributes:
        mu: True incident rate per 200,000 exposure hours.
        alpha: True NB2 dispersion.
        pi: True structural-zero probability.
        implausible_share: Fraction of filings given a corrupted hours value.
        n_per_year: Establishments simulated per reporting year.
        years: Reporting years to simulate.
        seed: RNG seed.
    """

    mu: float = 3.2
    alpha: float = 1.4
    pi: float = 0.18
    implausible_share: float = 0.02
    n_per_year: int = 3000
    years: Sequence[int] = (2021, 2022, 2023, 2024)
    seed: int = 12345

    def to_json(self) -> dict:
        """Return a JSON-serialisable dict of these parameters."""
        return {
            "mu": self.mu,
            "alpha": self.alpha,
            "pi": self.pi,
            "implausible_share": self.implausible_share,
            "n_per_year": self.n_per_year,
            "years": list(self.years),
            "seed": self.seed,
        }


def _rzinb(
    rng: np.random.Generator, mean: np.ndarray, alpha: float, pi: float
) -> np.ndarray:
    """Draw zero-inflated negative binomial counts.

    NB2 is generated as a gamma-Poisson mixture: ``y ~ Poisson(mean * G)`` with
    ``G ~ Gamma(shape=1/alpha, scale=alpha)``, which has mean 1 and variance
    ``alpha``, giving ``Var(y) = mean + alpha * mean^2``.

    Args:
        rng: Random generator.
        mean: Per-observation NB2 mean.
        alpha: Dispersion.
        pi: Structural-zero probability.

    Returns:
        Integer counts.
    """
    r = 1.0 / alpha
    gam = rng.gamma(shape=r, scale=1.0 / r, size=mean.shape)
    y = rng.poisson(mean * gam)
    structural = rng.random(mean.shape) < pi
    return np.where(structural, 0, y).astype(int)


def generate(params: GeneratorParams) -> Dict[int, List[Dict[str, object]]]:
    """Build the synthetic records, keyed by reporting year.

    Args:
        params: Ground-truth generator parameters.

    Returns:
        Mapping of year to a list of row dicts.
    """
    rng = np.random.default_rng(params.seed)
    naics_pool = ["3251", "3252", "3115", "2361", "6221", "4841", "4451", "3328"]
    out: Dict[int, List[Dict[str, object]]] = {}
    next_id = 1

    for yi, year in enumerate(params.years):
        n = params.n_per_year
        employees = np.clip(
            np.round(rng.lognormal(mean=3.9, sigma=1.15, size=n)), 1, 40000
        ).astype(int)
        hours_per_emp = np.clip(rng.normal(1850, 260, size=n), 200, 3200)
        hours = np.round(employees * hours_per_emp).astype(np.int64)

        exposure = hours / 200000.0
        # Mild year drift so stability code has something to measure.
        mu_year = params.mu * (1.0 + 0.03 * yi)
        counts = _rzinb(rng, exposure * mu_year, params.alpha, params.pi)

        # Corrupt a fraction of hours values by a power of ten, as happens when
        # a filer types an extra digit or reports company-wide hours at a site.
        n_bad = int(round(params.implausible_share * n))
        bad_idx = rng.choice(n, size=n_bad, replace=False)
        multipliers = rng.choice([10, 100, 1000, 100000], size=n_bad)
        hours = hours.copy()
        hours[bad_idx] = hours[bad_idx] * multipliers

        naics = rng.choice(naics_pool, size=n)
        dafw = rng.binomial(counts, 0.35)
        djtr = rng.binomial(np.maximum(counts - dafw, 0), 0.35)
        other = counts - dafw - djtr
        deaths = np.zeros(n, dtype=int)

        rows: List[Dict[str, object]] = []
        for i in range(n):
            rec = int(deaths[i] + dafw[i] + djtr[i] + other[i])
            rows.append(
                {
                    "id": next_id,
                    "company_name": f"SYNTHETIC COMPANY {i:05d}",
                    "establishment_name": f"SYNTHETIC SITE {i:05d}",
                    "ein": "",
                    "street_address": "1 Example Way",
                    "city": "Nowhere",
                    "state": "ZZ",
                    "zip_code": "00000",
                    "naics_code": naics[i],
                    "naics_year": 2017,
                    "industry_description": "SYNTHETIC INDUSTRY",
                    "annual_average_employees": int(employees[i]),
                    "total_hours_worked": int(hours[i]),
                    "no_injuries_illnesses": 1 if rec > 0 else 2,
                    "total_deaths": int(deaths[i]),
                    "total_dafw_cases": int(dafw[i]),
                    "total_djtr_cases": int(djtr[i]),
                    "total_other_cases": int(other[i]),
                    "total_dafw_days": int(dafw[i] * 7),
                    "total_djtr_days": int(djtr[i] * 4),
                    "total_injuries": rec,
                    "total_poisonings": 0,
                    "total_respiratory_conditions": 0,
                    "total_skin_disorders": 0,
                    "total_hearing_loss": 0,
                    "total_other_illnesses": 0,
                    "establishment_id": 100000 + i,
                    "establishment_type": 1,
                    "size": 2,
                    "year_filing_for": year,
                    "created_timestamp": f"1/1/{year + 1}",
                    "change_reason": "",
                }
            )
            next_id += 1
        out[year] = rows
    return out


def write_fixture(out_dir: Path, params: GeneratorParams) -> List[Path]:
    """Write the fixture CSVs and their synthetic-data declarations.

    Args:
        out_dir: Directory to write into.
        params: Generator parameters.

    Returns:
        Paths written.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    data = generate(params)
    written: List[Path] = []

    for year, rows in data.items():
        cols = PRE2023_COLUMNS if year < 2023 else POST2023_COLUMNS
        path = out_dir / f"SYNTHETIC_ITA_300A_{year}.csv"
        with path.open("w", newline="", encoding="utf-8") as fh:
            w = csv.DictWriter(fh, fieldnames=list(cols), extrasaction="ignore")
            w.writeheader()
            for r in rows:
                w.writerow({c: r.get(c, "") for c in cols})
        written.append(path)
        header_path = path.with_suffix(".HEADER.txt")
        header_path.write_text(SYNTHETIC_HEADER + "\n", encoding="utf-8")
        written.append(header_path)

    truth = out_dir / "GROUND_TRUTH.json"
    import json

    truth.write_text(
        json.dumps(
            {"declaration": SYNTHETIC_HEADER, "parameters": params.to_json()}, indent=2
        )
        + "\n",
        encoding="utf-8",
    )
    written.append(truth)
    return written


def build_parser() -> argparse.ArgumentParser:
    """Construct the command-line parser."""
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--out", type=Path, default=Path(__file__).resolve().parent / "fixture"
    )
    p.add_argument("--n", type=int, default=3000, help="Establishments per year.")
    p.add_argument("--seed", type=int, default=12345)
    return p


def main(argv: list[str] | None = None) -> int:
    """Entry point.

    Args:
        argv: Command-line arguments; defaults to ``sys.argv[1:]``.

    Returns:
        Process exit code.
    """
    args = build_parser().parse_args(argv)
    params = GeneratorParams(n_per_year=args.n, seed=args.seed)
    paths = write_fixture(args.out, params)
    print(SYNTHETIC_HEADER)
    for p in paths:
        print(f"  wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
